### ISSUE TITLE
Unhandled event loop exception, java.lang.NullPointerException giving invalid score or empty values while add rule

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#206]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores. 
1. Add rule. 
1. Select scores, give an invalid value, for example 2.
1. Click Add button. 

**Expected results**
* Input number is out of range error message and no exception in log. 

**Received results**
* The error popup was right, but the log contains exception: 
```
!ENTRY org.eclipse.ui 4 0 2021-05-11 10:56:43.151
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.eclipse.sed.ifl.ide.gui.rulecreator.NegatableRuleCreator.getRule(NegatableRuleCreator.java:77)
	at org.eclipse.sed.ifl.ide.gui.dialogs.RuleCreatorDialog$1.widgetSelected(RuleCreatorDialog.java:95)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3986)
```
Full log file: 
[unhandled_nullpointer_log.txt](https://github.com/InteractiveFaultLocalization/iFL4Eclipse/files/6457895/unhandled_nullpointer_log.txt)

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.6
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.206.1

**Comment by brita-sed** [comment]
There wasn't any error in log, the bug has been corrected.
